version: "3.8"

services:
  apigateway:
    build:
      context: .
      dockerfile: Infrabot.BotManagement.ApiGateway/Dockerfile
    container_name: bot-management-backend-apigateway
    ports:
      - "5002:5002"
    networks:
      - infrabot_network

networks:
  infrabot_network:
    driver: bridge
