version: '3.4'

services:
  infrabot-api:
    image: infrabot-api
    build:
      context: .
      dockerfile: Infrabot.BotManagement.ApiGateway/Dockerfile
    ports:
      - "5002:5002"
      - "6002:6002"
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
    volumes:
        - /etc/nginx/ssl:/etc/ssl/certs
    networks:
        - infrabot-network

networks:
  infrabot-network:
    driver: bridge