version: '3.8'

services:
  api-gateway:
    image: infrabot-api-gateway
    build:
      context: .
      dockerfile: Infrabot.BotManagement.ApiGateway/Dockerfile
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_URLS=https://+:5002
      - ASPNETCORE_ENVIRONMENT=Production
    restart: unless-stopped
